version: '3'

services:
  tourdb:
    image: postgres:10-alpine
    container_name: tournamentor
    volumes:
      - ./.db
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5429:5432
