# Generated by Django 2.2.6 on 2019-10-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20191014_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='tour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
