# Generated by Django 2.2.6 on 2019-10-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20191019_1505'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['tour_type', 'tour_id'], name='tournaments_tour_ty_25573a_idx'),
        ),
    ]
