# Generated by Django 2.2.6 on 2019-10-14 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20191014_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knockouttour',
            name='knockout_legs',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
