# Generated by Django 2.2.6 on 2019-10-16 03:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='players.Player')),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_b', to='players.Player')),
                ('player_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_c', to='players.Player')),
                ('player_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_d', to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_result', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('away_result', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('away_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_club', to='clubs.Club')),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='games.Team')),
                ('home_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_club', to='clubs.Club')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='games.Team')),
            ],
        ),
    ]
