# Generated by Django 2.2.6 on 2019-10-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tie_type',
            field=models.CharField(choices=[('Single-legged', 'single'), ('Two-legged', 'twotie')], default='Single-legged', max_length=30),
        ),
    ]
