# Generated by Django 2.2.6 on 2019-10-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191013_0448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoLeggedTie',
        ),
    ]
