# Generated by Django 2.2.6 on 2019-10-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('games', '0003_delete_twoleggedtie'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
