# Generated by Django 2.2.6 on 2019-10-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('position', models.CharField(max_length=300)),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('stats', models.TextField()),
            ],
        ),
    ]
