# Generated by Django 2.2.6 on 2019-10-15 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191015_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{6}')]),
        ),
    ]
